// This file is automatically generated by prisma-custom-nanoid.
// Do not edit it directly. Update the Prisma schema and run prisma generate instead.

export const customNanoidConfig = {
  models: {
    ApiKey: {
      field: "id",
      alphabet: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ",
      size: 24,
    },
    Post: {
      field: "id",
      alphabet: "abcdefghijklmnopqrstuvwxyz",
      size: 12,
    },
    User: {
      field: "id",
      alphabet: "0123456789abcdefghijklmnopqrstuvwxyz",
      size: 16,
    },
  },
  relations: {
    Post: {
      author: "User",
    },
    User: {
      posts: "Post",
    },
  },
} as const;
