// This file is automatically generated by prisma-custom-nanoid.
// Do not edit it directly. Update the Prisma schema and run prisma generate instead.

export const customNanoidRelations = {
  Post: {
    author: "User",
  },
  User: {
    posts: "Post",
  },
} as const;
