import { describe, expect, it } from "vitest";
import {
  buildRelations,
  renderRelationsModule,
} from "../src/generator-output.js";

describe("relations generator", () => {
  it("object field だけから全 relation mapping を決定的に生成する", () => {
    const relations = buildRelations([
      {
        name: "User",
        fields: [
          { name: "posts", kind: "object", type: "Post" },
          { name: "email", kind: "scalar", type: "String" },
          { name: "account", kind: "object", type: "Account" },
        ],
      },
      {
        name: "Account",
        fields: [{ name: "users", kind: "object", type: "User" }],
      },
      {
        name: "ApiKey",
        fields: [{ name: "id", kind: "scalar", type: "String" }],
      },
    ]);

    expect(relations).toEqual({
      Account: { users: "User" },
      User: {
        account: "Account",
        posts: "Post",
      },
    });
  });

  it("再生成可能な TypeScript module を出力する", () => {
    expect(
      renderRelationsModule({
        User: { posts: "Post" },
      }),
    ).toBe(`// This file is automatically generated by prisma-custom-nanoid.
// Do not edit it directly. Update the Prisma schema and run prisma generate instead.

export const customNanoidRelations = {
  User: {
    posts: "Post",
  },
} as const;
`);
  });
});
