import { describe, expect, it } from "vitest";
import {
  buildConfiguration,
  buildModels,
  buildRelations,
  renderConfigurationModule,
} from "../src/generator-output.js";
import { customNanoidConfig } from "./fixtures/generated-custom-nanoid/index.js";

describe("configuration generator", () => {
  it("field directives and nanoid defaults produce model configurations", () => {
    expect(
      buildModels([
        {
          name: "User",
          fields: [
            {
              name: "id",
              kind: "scalar",
              type: "String",
              documentation:
                'Primary identifier\n@customNanoid(alphabet: "01\\\\\\"")',
              default: { name: "nanoid", args: [14] },
            },
          ],
        },
        {
          name: "ApiKey",
          fields: [
            {
              name: "id",
              kind: "scalar",
              type: "String",
              documentation: '@customNanoid(alphabet: "abc")',
              default: { name: "nanoid", args: [] },
            },
          ],
        },
      ]),
    ).toEqual({
      ApiKey: { field: "id", alphabet: "abc", size: 21 },
      User: { field: "id", alphabet: '01\\"', size: 14 },
    });
  });

  it("object fields produce a deterministic relation mapping", () => {
    const fields = [
      { name: "posts", kind: "object", type: "Post" },
      { name: "email", kind: "scalar", type: "String" },
      { name: "account", kind: "object", type: "Account" },
    ];
    const models = [
      { name: "User", fields },
      {
        name: "Account",
        fields: [{ name: "users", kind: "object", type: "User" }],
      },
      {
        name: "ApiKey",
        fields: [{ name: "id", kind: "scalar", type: "String" }],
      },
    ];

    expect(buildRelations(models)).toEqual({
      Account: { users: "User" },
      User: {
        account: "Account",
        posts: "Post",
      },
    });
    expect(models[0]?.fields.map((field) => field.name)).toEqual([
      "posts",
      "email",
      "account",
    ]);
  });

  it("renders a complete reusable configuration module", () => {
    expect(
      renderConfigurationModule({
        models: {
          User: { field: "id", alphabet: "01", size: 14 },
        },
        relations: {
          User: { posts: "Post" },
        },
      }),
    ).toBe(`// This file is automatically generated by prisma-custom-nanoid.
// Do not edit it directly. Update the Prisma schema and run prisma generate instead.

export const customNanoidConfig = {
  models: {
    User: {
      field: "id",
      alphabet: "01",
      size: 14,
    },
  },
  relations: {
    User: {
      posts: "Post",
    },
  },
} as const;
`);
  });

  it("matches the generated fixture", () => {
    expect(customNanoidConfig).toEqual(
      buildConfiguration([
        {
          name: "User",
          fields: [
            {
              name: "id",
              kind: "scalar",
              type: "String",
              documentation: '@customNanoid(alphabet: "abc123")',
              default: { name: "nanoid", args: [12] },
            },
            { name: "posts", kind: "object", type: "Post" },
            { name: "tokens", kind: "object", type: "Token" },
          ],
        },
        {
          name: "Post",
          fields: [
            {
              name: "id",
              kind: "scalar",
              type: "String",
              documentation: '@customNanoid(alphabet: "def456")',
              default: { name: "nanoid", args: [10] },
            },
            { name: "author", kind: "object", type: "User" },
            { name: "comments", kind: "object", type: "Comment" },
          ],
        },
        {
          name: "Comment",
          fields: [
            {
              name: "id",
              kind: "scalar",
              type: "String",
              documentation: '@customNanoid(alphabet: "ghi789")',
              default: { name: "nanoid", args: [9] },
            },
            { name: "post", kind: "object", type: "Post" },
          ],
        },
        {
          name: "ApiKey",
          fields: [
            {
              name: "id",
              kind: "scalar",
              type: "String",
              documentation: '@customNanoid(alphabet: "xyz789")',
              default: { name: "nanoid", args: [8] },
            },
          ],
        },
        {
          name: "Token",
          fields: [
            {
              name: "id",
              kind: "scalar",
              type: "String",
              documentation: '@customNanoid(alphabet: "tuv456")',
              default: { name: "nanoid", args: [7] },
            },
            { name: "project", kind: "object", type: "Project" },
            { name: "user", kind: "object", type: "User" },
          ],
        },
        {
          name: "Account",
          fields: [{ name: "projects", kind: "object", type: "Project" }],
        },
        {
          name: "Project",
          fields: [
            { name: "account", kind: "object", type: "Account" },
            { name: "tokens", kind: "object", type: "Token" },
          ],
        },
      ]),
    );
  });

  it.each([
    [
      [
        {
          name: "User",
          fields: [{ name: "id", kind: "scalar", type: "String" }],
        },
      ],
      "no @customNanoid fields",
    ],
    [
      [
        {
          name: "User",
          fields: [
            {
              name: "id",
              kind: "scalar",
              type: "String",
              documentation: "@customNanoid(alphabet: abc)",
              default: { name: "nanoid", args: [10] },
            },
          ],
        },
      ],
      "invalid @customNanoid directive",
    ],
    [
      [
        {
          name: "User",
          fields: [
            {
              name: "id",
              kind: "scalar",
              type: "String",
              documentation: '@customNanoid(alphabet: "")',
              default: { name: "nanoid", args: [10] },
            },
          ],
        },
      ],
      "alphabet must contain",
    ],
    [
      [
        {
          name: "User",
          fields: [
            {
              name: "id",
              kind: "scalar",
              type: "String",
              documentation: `@customNanoid(alphabet: "${"a".repeat(257)}")`,
              default: { name: "nanoid", args: [10] },
            },
          ],
        },
      ],
      "alphabet must contain",
    ],
    [
      [
        {
          name: "User",
          fields: [
            {
              name: "id",
              kind: "scalar",
              type: "String",
              documentation:
                '@customNanoid(alphabet: "abc")\n@customNanoid(alphabet: "def")',
              default: { name: "nanoid", args: [10] },
            },
          ],
        },
      ],
      "exactly one @customNanoid directive",
    ],
    [
      [
        {
          name: "User",
          fields: [
            {
              name: "id",
              kind: "scalar",
              type: "Int",
              documentation: '@customNanoid(alphabet: "abc")',
              default: { name: "autoincrement", args: [] },
            },
          ],
        },
      ],
      "scalar String field",
    ],
    [
      [
        {
          name: "User",
          fields: [
            {
              name: "id",
              kind: "scalar",
              type: "String",
              documentation: '@customNanoid(alphabet: "abc")',
              default: { name: "uuid", args: [] },
            },
          ],
        },
      ],
      "must use @default(nanoid())",
    ],
    [
      [
        {
          name: "User",
          fields: [
            {
              name: "id",
              kind: "scalar",
              type: "String",
              documentation: '@customNanoid(alphabet: "abc")',
              default: { name: "nanoid", args: [0] },
            },
          ],
        },
      ],
      "size must be a positive integer",
    ],
    [
      [
        {
          name: "User",
          fields: [
            {
              name: "id",
              kind: "scalar",
              type: "String",
              documentation: '@customNanoid(alphabet: "abc")',
              default: { name: "nanoid", args: [10] },
            },
            {
              name: "externalId",
              kind: "scalar",
              type: "String",
              documentation: '@customNanoid(alphabet: "def")',
              default: { name: "nanoid", args: [10] },
            },
          ],
        },
      ],
      "multiple @customNanoid fields",
    ],
  ])("rejects invalid schema metadata", (models, message) => {
    expect(() => buildModels(models)).toThrow(TypeError);
    expect(() => buildModels(models)).toThrow(message);
  });
});
