// This file is automatically generated by prisma-custom-nanoid.
// Do not edit it directly. Update the Prisma schema and run prisma generate instead.

export const customNanoidConfig = {
  models: {
    ApiKey: {
      field: "id",
      alphabet: "xyz789",
      size: 8,
    },
    Comment: {
      field: "id",
      alphabet: "ghi789",
      size: 9,
    },
    Post: {
      field: "id",
      alphabet: "def456",
      size: 10,
    },
    Token: {
      field: "id",
      alphabet: "tuv456",
      size: 7,
    },
    User: {
      field: "id",
      alphabet: "abc123",
      size: 12,
    },
  },
  relations: {
    Account: {
      projects: "Project",
    },
    Comment: {
      post: "Post",
    },
    Post: {
      author: "User",
      comments: "Comment",
    },
    Project: {
      account: "Account",
      tokens: "Token",
    },
    Token: {
      project: "Project",
      user: "User",
    },
    User: {
      posts: "Post",
      tokens: "Token",
    },
  },
} as const;
