// This file is automatically generated by prisma-custom-nanoid.
// Do not edit it directly. Update the Prisma schema and run prisma generate instead.

export const customNanoidRelations = {
  Account: {
    projects: "Project",
  },
  Comment: {
    post: "Post",
  },
  Post: {
    author: "User",
    comments: "Comment",
  },
  Project: {
    account: "Account",
    tokens: "Token",
  },
  Token: {
    project: "Project",
    user: "User",
  },
  User: {
    posts: "Post",
    tokens: "Token",
  },
} as const;
