interface DmmfFieldLike {
  name: string;
  kind: string;
  type: string;
}

interface DmmfModelLike {
  name: string;
  fields: readonly DmmfFieldLike[];
}

export type GeneratedRelations = Readonly<
  Record<string, Readonly<Record<string, string>>>
>;

function compareNames(left: string, right: string): number {
  if (left < right) {
    return -1;
  }
  if (left > right) {
    return 1;
  }
  return 0;
}

export function buildRelations(
  models: readonly DmmfModelLike[],
): GeneratedRelations {
  const relations: Record<string, Record<string, string>> = {};

  for (const model of [...models].sort((left, right) =>
    compareNames(left.name, right.name),
  )) {
    const fields = model.fields
      .filter((field) => field.kind === "object")
      .sort((left, right) => compareNames(left.name, right.name));
    if (fields.length === 0) {
      continue;
    }

    relations[model.name] = Object.fromEntries(
      fields.map((field) => [field.name, field.type]),
    );
  }

  return relations;
}

export function renderRelationsModule(relations: GeneratedRelations): string {
  const models = Object.entries(relations);
  const body =
    models.length === 0
      ? "{}"
      : `{\n${models
          .map(
            ([model, fields]) =>
              `  ${model}: {\n${Object.entries(fields)
                .map(
                  ([field, targetModel]) =>
                    `    ${field}: ${JSON.stringify(targetModel)},`,
                )
                .join("\n")}\n  },`,
          )
          .join("\n")}\n}`;

  return `// This file is automatically generated by prisma-custom-nanoid.
// Do not edit it directly. Update the Prisma schema and run prisma generate instead.

export const customNanoidRelations = ${body} as const;
`;
}
